### ISSUE TITLE
SSL certs expired

### ISSUE THREAD

**Issue by ragesoss** [wikiwho/WikiWho#2]
The WikiWho API has an SSL cert that expired today.

**Comment by bitnik** [comment]
Hey @ragesoss, thanks a lot. There was a problem with cronjob. Now certs are renewed.

**Comment by ragesoss** [comment]
Thanks much!

**Comment by ragesoss** [comment]
Looks like this happened again. api.wikiwho.net's SSL certs expired today.

**Comment by wikiwho** [comment]
Fixed. Weirdly, the local version was listed as expiring on 27th of
december, that's why no renewal triggered. Will investigate.

**Comment by ragesoss** [comment]
Thank you!

**Comment by ragesoss** [comment]
The cert is expired again.

**Comment by ragesoss** [comment]
Cert is working now.
